/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader convert_BMToDSFE
(
    color BaseColor = color(0.5),
    float Metallic = 0.0,

    color DielectricFace = color(0.04),
    color DielectricEdge = color(1.0),
    color MetallicAlbedo = color(0.0),

    output color Diffuse = color(0.0),
    output color SpecularFace = color(0.0),
    output color SpecularEdge = color(0.0)
)
{
    Diffuse = mix( BaseColor, MetallicAlbedo, Metallic );
    SpecularFace = mix( DielectricFace, BaseColor, Metallic );
    SpecularEdge = mix( DielectricEdge, BaseColor, Metallic );
}
