/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader convert_ColorToFloat
(
    float Gain = 1.0,
    color Color = color(1.0),

    output float R = 0.0,
    output float G = 0.0,
    output float B = 0.0,
    output float AvgRGB = 0.0
)
{
    R = Gain * Color.r;
    G = Gain * Color.g;
    B = Gain * Color.b;
    AvgRGB = ( R + G + B ) / 3.0;
}
