/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader convert_DeltaPToBump
(
    vector DeltaP = vector(0.0),
    float  Gain = 1.0,

    output vector SurfaceGradient = vector(0.0),
    output normal Normal = normal(0.0)
)
{
    // Must reference P for auto-differentiation to work.
    point Po = P;
    getattribute( "builtin", "Po", Po );

    // Compute the bumped normal from the displaced point.
    point Pdisp = Po + Gain*DeltaP;
    normal Nbump = calculatenormal( Pdisp );

    // Mikkelsen, M. 2020
    // Surface Gradient–Based Bump Mapping Framework
    // Journal of Computer Graphics Techniques, Vol. 9, No. 3
    // https://jcgt.org/published/0009/03/04/
    float k = dot( N, Nbump );
    SurfaceGradient = ( k*N - Nbump )/max( 1.0e-6, abs(k) );

    // Convert it to a shading Normal.
    Normal = normalize( N - SurfaceGradient );
}
