/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader convert_FloatToColor
(
    float Gain = 1.0,
    float R = 1.0,
    float G = 1.0,
    float B = 1.0,

    output color Color = color( 0.0 )
)
{
    Color = Gain * color( R, G, B );
}
