/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader convert_SFEToNK
(
    color SpecularFace = color(0.0),
    color SpecularEdge = color(1.0),

    output color n = color(0.0),
    output color k = color(0.0)
)
{
    float square( float x ) { return x*x; }

    // Gulbrandsen, O. 2014
    // Artistic Friendly Metallic Fresnel
    // Journal of Computer Graphics Techniques Vol. 3, No. 4
    // http://jcgt.org/published/0003/04/03/
    float f0f90_to_eta( float f0, float f90 )
    {
        float eta = ( 1.0-f0 )/( 1.0+f0 );
        float sqrt_f0 = sqrt( f0 );
        float eta_max = ( 1.0+sqrt_f0 )/( 1.0-sqrt_f0 );

        eta_max = select( 1.0e6, eta_max, isfinite(eta_max) );

        return mix( eta_max, eta, f90 );
    }

    float f0eta_to_k( float f0, float eta )
    {
        float nr = f0*square( eta+1.0 ) - square( eta-1.0 );
        float k = sqrt( nr/( 1.0-f0 ));

        return select( 1.0, k, isfinite(k) );
    }

    color f0f90_to_eta( color f0, color f90 )
    {
        return color(
                f0f90_to_eta( f0[0], f90[0] ),
                f0f90_to_eta( f0[1], f90[1] ),
                f0f90_to_eta( f0[2], f90[2] )
                );
    }
    color f0eta_to_k( color f0, color eta )
    {
        return color(
                f0eta_to_k( f0[0], eta[0] ),
                f0eta_to_k( f0[1], eta[1] ),
                f0eta_to_k( f0[2], eta[2] )
                );
    }

    color eta = f0f90_to_eta( SpecularFace, SpecularEdge );
    k = f0eta_to_k( SpecularFace, eta );

    n = color(1)/eta;
    n = select( color(1.0e6), n, color( isfinite(n[0]), isfinite(n[1]), isfinite(n[2]) ));
}