/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader convert_SGToN
(
    vector SurfaceGradient = vector(0.0),
    float Gain = 1.0,

    output normal Normal = normal(0.0)
)
{
    Normal = normalize( N - SurfaceGradient*Gain );
}
