/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader builtin_Id
(
    output color Id_color = color(0.0)
)
{
    int Id, Id2;
    getattribute( "builtin", "Id", Id );
    getattribute( "builtin", "Id2", Id2 );

    point Id_point = point( Id, Id2, 0 );
    Id_color = noise( "cell", Id_point );
}
