/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader builtin_Non
(
    output color Non_color = color(0.0)
)
{
    normal Non;
    getattribute( "builtin", "Non", Non );
    Non = transform( "common", "object", Non );
    Non = normalize( Non );

    Non_color = abs( Non );
}
