/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader builtin_Po
(
    output color Po_color = color(0.0)
)
{
    point Po;
    getattribute( "builtin", "Po", Po );
    Po = transform( "common", "object", Po );

    Po_color = Po - floor( Po );
}
