/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader modify_Contrast
(
    float in = 0.5,
    float inAvg = 0.5,

    color In = color(0.5),
    color InAvg = color(0.5),

    float Contrast = 1.0,

    output float out = 0.0,
    output color Out = color(0.0)
)
{
    // Contrast adjust the patterns.
    out = mix( inAvg, in, Contrast );
    Out = mix( InAvg, In, Contrast );
}
