/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader coordinate_system
(
    string space = "object",
    output color space_color = color(0.0)
)
{
    point space_P;
    space_P = transform( "common", space, P );

    space_color = space_P - floor( space_P );
}
