/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader displace_Height
(
    float  Height = 0.5,
    float  Offset = 0.0,
    float  Magnitude = 1.0,
    string MagnitudeSpace = "world",
    int    Invert = 0,

    output vector DeltaP = vector(0.0)
)
{
    // Invert?
    float height = Height;
    if( Invert ) height = 1.0-height;

    // [0,1] Height value shifts the surface ±0.5
    // plus the Offset.
    height = height-0.5 + Offset;

    // Apply the Magnitude.
    height *= Magnitude;

    // Scale height to common space.
    matrix mag_to_common;

    if( getmatrix( MagnitudeSpace, "common", mag_to_common ))
    {
        height *= pow( abs( determinant( mag_to_common )), 0.33333333 );
    }
    else
    {
        warning(
            "Magnitude Space = \"%s\" couldn't be found. "
            "Using \"common\" space instead - that's not good. ",
            MagnitudeSpace
            );
    }

    // The change in the surface point P.
    DeltaP = N * height;
}
