/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader displace_Vector
(
    vector Vector = vector(0.0),
    float  Magnitude = 1.0,
    string MagnitudeSpace = "world",
    int    Negate = 0,

    output vector DeltaP = vector(0.0)
)
{
    // Invert?
    vector deltaP = Vector;
    if( Negate ) deltaP = -deltaP;

    // Apply the Magnitude.
    deltaP *= Magnitude;

    // Scale to common space.
    matrix mag_to_common;

    if( getmatrix( MagnitudeSpace, "common", mag_to_common ))
    {
        deltaP *= pow( abs( determinant( mag_to_common )), 0.33333333 );
    }
    else
    {
        warning(
            "Magnitude Space = \"%s\" couldn't be found. "
            "Using \"common\" space instead - that's not good. ",
            MagnitudeSpace
            );
    }

    // The change in the surface.
    DeltaP = deltaP;
}
