/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader primvar_Nref
(
    output color Nref_color = color(0.0)
)
{
    normal Nref;
    getattribute( "primvar", "__Nref", Nref );
    Nref = transform( "common", "object", Nref );

    Nref_color = abs( Nref );
}
