/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader primvar_st
(
    float s = u [[int lockgeom=0]],
    float t = v [[int lockgeom=0]],

    output color st_color = color(0.0)
)
{
    st_color = color( s, t, 0 );
}
