/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader space_2D
(
    int Coordinates = 0, // 0:Texture UV 1:PrimVar 2:Geo uv
    string PrimitiveVariable = "st",

    output point Out = point(0.0),

    float s = u [[ int lockgeom = 0 ]],
    float t = v [[ int lockgeom = 0 ]]
)
{
    // Get st space: the Texture UV's.
    Out = point( s, t, 0 );

    // Primitive Variable.
    if( 1 == Coordinates )
    {
        float primvar[2];
        if( getattribute( "primvar", PrimitiveVariable, primvar ))
        {
            Out.x = primvar[0];
            Out.y = primvar[1];
        }
    }

    // Geometric uv.
    else if( 2 == Coordinates )
    {
        Out.x = u;
        Out.y = v;
    }
}
