/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader space_3D
(
    int DisplacedP = 0,
    string Coordinates = "object", // Set to "Primitive Variable" to use it instead.
    string PrimitiveVariable = "__Pref",
    string SizeSpace = "world",

    output point Out = point(0.0)
)
{
    // Referencing P is required for any down-stream auto-differentiation.
    Out = P;

    // Replace with un-displaced P?
    if( !DisplacedP ) getattribute( "builtin", "Po", Out );

    // Check for "Primitive Variable" Coordinates.
    if( "Primitive Variable" == Coordinates )
    {
        if( !getattribute( "primvar", PrimitiveVariable, Out ))
        {
            warning(
                "A point-type Primitive Variable = \"%s\" wasn't found. "
                "Using \"object\" Coordinates instead.",
                PrimitiveVariable
                );
        }
    }

    // Restore the original primvar values,
    // or start with "object" Coordinates.
    Out = transform( "common", "object", Out );

    if( "Primitive Variable" != Coordinates )
    {
        matrix object_to_coord;
        if( getmatrix( "object", Coordinates, object_to_coord ))
        {
            // Transform to Coordinates.
            Out = transform( object_to_coord, Out );

            // Apply SizeSpace scale.
            matrix coord_to_size;
            if( getmatrix( Coordinates, SizeSpace, coord_to_size ))
            {
                Out *= pow( abs( determinant( coord_to_size )), 0.33333333 );
            }
            else
            {
                warning( "Size Space = \"%s\" wasn't found.", SizeSpace );
            }
        }
        else
        {
            warning( "Coordinates = \"%s\" wasn't found.", Coordinates );
        }
    }
}
