/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader space_Spherical
(
    point In = point(0),
    int   Axis = 1, // 0 = X, 1 = Y, 2 = Z
    output point Out = point(0)
)
{
    // Initialize the 3d space.
    if( isconnected( In )) Out = In;
    else Out = transform( "common", "object", P );

    // Select the projection axis.
    if( 0 == Axis )
    {
        Out = point( Out.y, Out.z, Out.x );
    }
    else if( 1 == Axis )
    {
        Out = point( Out.x, Out.z, Out.y );
    }
    else if( 2 == Axis )
    {
        Out = point( Out.x, Out.y, Out.z );
    }

    // Spherical projection.
    Out = normalize( vector( Out ));
    Out.x = atan2( Out.y, Out.x ) / M_2PI;
    Out.y = asin( Out.z ) / M_PI_2;
    Out.z = 0.0;
}
