/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader common_space
(
    output point Pdisp = point(0.0),
    output color RGB = color(0.0)
)
{
    float height = noise( P );

    Pdisp = P + N*height;
    RGB = color( height );
}
