/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader pattern_FractalNoise
(
    point  Space = point(0.0),
    float  Size = 1.0,
    string Type = "uperlin",
    float  Variation = 0.0,

    float  Dimension = 1.0,
    float  Lacunarity = 2.0,
    float  Erosion = 0.0,
    int    Iterations = 5,

    output color RGB = color(0.0)
)
{
    // Pattern generation space.
    point Q = Space;

    if( !isconnected( Space ))
    {
        Q = P;
        getattribute( "primvar", "__Pref", Q );
        Q = transform( "common", "object", Q );
    }

    // Size scaling.
    Q /= max( 1.0e-6, Size );

    // Initialize the iteration variables.
    float freqi = 1.0;
    float sum = 0.0;
    float mag = 1.0;

    RGB = color(0.0);

    // Compute the fractal.
    for( int i=0; i < Iterations; i++ )
    {
        // This iteration’s frequency.
        point Qi = Q*freqi;

        // Accumulate this iteration’s noise pattern.
        RGB += noise( Type, Qi, Variation ) * mag;

        // Update for the next iteration.
        freqi *= Lacunarity;
        sum += mag;

        // Erosion adjustment.
        float avg = ( RGB.r + RGB.g + RGB.b ) * 0.33333333;
        float erosion = mix( -Erosion, Erosion, avg/sum );

        // Fractal magnitude of the next iteration.
        mag = 1.0 / pow( freqi, 3.0-2.0*Dimension + erosion );
    }

    // Normalize the result.
    RGB /= sum;
}
