/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader pattern_Gabor
(
    point  Space = point(0.0),
    float  Size = 1.0,

    output color RGB = color(0.0)
)
{
    // Pattern generation space.
    point Q = Space;

    if( !isconnected( Space ))
    {
        Q = P;
        getattribute( "primvar", "__Pref", Q );
        Q = transform( "common", "object", Q );
    }

    color n = noise( "gabor", Q );

    RGB = 0.5*n + color(0.5);
}
