/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader pattern_Sine
(
    point Space = point(0.0),
    float Size = 1.0,

    output color RGB = color(0.0)
)
{
    // Pattern generation space.
    point Q = Space;

    if( !isconnected( Space ))
    {
        Q = P;
        getattribute( "primvar", "__Pref", Q );
        Q = transform( "common", "object", Q );
    }

    // Size scaling.
    Q /= max( 0.00001, Size );

    // Sine.
    Q = linearstep( -1.0, 1.0, sin( Q*M_2PI ));

    RGB = color( Q );
}
