/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader pattern_Smoothstep
(
    point Space = point(0.0),
    float Size = 1.0,
    float DutyCycle = 0.5,

    output color RGB = color(0.0),
    output color Gray = color(0.0),
    output float Float = 0.0
)
{
    // Pattern generation space.
    point Q = Space;

    if( !isconnected( Space ))
    {
        Q = P;
        getattribute( "primvar", "__Pref", Q );
        Q = transform( "common", "object", Q );
    }

    // Size scaling.
    Q /= max( 0.00001, Size );

    // Triangle.
    Q = 2 * min( mod(Q,1), mod(-Q,1) );

    // End points.
    float a = linearstep( 0.5, 1.0, 1.0-DutyCycle );
    float b = linearstep( 0.0, 0.5, 1.0-DutyCycle );

    // Smooth it out.
    Q = smoothstep( a, b , Q );

    RGB = color( Q );

    Float = Q.x;
    Float = mix( Float, 1.0-Float, Q.y );
    Float = mix( Float, 1.0-Float, Q.z );

    Gray = color( Float );
}
