/*
 *  Copyright 2024 LAIKA. Authored by Mitch Prater
 *
 *  Licensed under the Apache License Version 2.0 http://apache.org/licenses/LICENSE-2.0,
 *  or the MIT license http://opensource.org/licenses/MIT, at your option.
 *
 *  This file may not be copied, modified, or distributed except according to those terms.
 */
shader pattern_Worley
(
    point Space = point(0.0),
    float Size = 1.0,
    float Jitter = 1.0,
    int   Invert = 0,

    output float F1 = 0.0,
    output float F2 = 0.0,
    output float F2minusF1 = 0.0,
    output color Voronoi = color(0.0),
    output point CellPoint = point(0.0)
)
{
    // Pattern generation space.
    point Q = Space;

    if( !isconnected( Space ))
    {
        Q = P;
        getattribute( "primvar", "__Pref", Q );
        Q = transform( "common", "object", Q );
    }

    // Size scaling.
    Q /= max( 1.0e-6, Size );

    // Divide Q into cells (unit cubes) and randomly place
    // a point within each. Then measure the distance between
    // the shaded point and the random point in each of the
    // 27 cells that contain it or are neighbors of it.
    F1 = F2 = 5.0; // Ensure these will be changed.

    // The shaded point’s cell index.
    point QIndex = floor( Q );

    for( int i = -1; i <= 1; i++ )
    {
        for( int j = -1; j <= 1; j++ )
        {
            for( int k = -1; k <= 1; k++ )
            {
                // The cell’s index and its random offset.
                point cellIndex = QIndex + vector(i, j, k);
                vector cellOffset = noise( "cell", cellIndex );

                // The cell’s jittered point.
                point cellQ = cellIndex + Jitter*cellOffset;

                // Euclidean distance measure to Q.
                float distance = length( vector( cellQ-Q ));

                // New F1 or F2?
                // if distance < F1:
                float newF1 = step( distance, F1 );
                // if F1 < distance < F2:
                float newF2 = mix( step( distance, F2 ), 0.0, newF1 );

                // New F1: update both.
                F2 = mix( F2, F1, newF1 );
                F1 = mix( F1, distance, newF1 );

                // New F2: update F2.
                F2 = mix( F2, distance, newF2 );

                // Update Voronoi color.
                Voronoi = mix( Voronoi, color(cellOffset), newF1 );

                // Update CellPoint location.
                CellPoint = mix( CellPoint, cellQ, newF1 );
            }
        }
    } // End loops.

    // Additional float output.
    F2minusF1 = F2 - F1;

    if( Invert )
    {
        F1 = 1.0 - F1;
        F2 = 1.0 - F2;
        F2minusF1 = 1.0 - F2minusF1;
    }
}